global:
  scrape_interval: 5s # Frequência alta para acompanharmos o teste de carga

scrape_configs:
  - job_name: 'bank-system-dynamic-sd'
    metrics_path: '/actuator/prometheus'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets.json'
        refresh_interval: 10s
